title: Mostly Revit...
author: Eric Stimmel
description: A blog mostly about Revit, but also sometimes about other things loosely related.
permalink: /:year/:month/:day/:title
paginate: 5
markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            class: 'line-%i'
plugins:
  - jekyll-feed