title: Mostly Revit...
author: Eric Stimmel
description: A blog mostly about Revit, but also sometimes about other things loosely related.
feed_url: http://blog.ericstimmel.com/feed.xml
permalink: /:year/:month/:day/:title
paginate: 5
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
        span:
            line_numbers: false
        block:
            class: 'line-%i'
            line_numbers: false
plugins:
  - jekyll-feed
