name: Eric Stimmel
title: Mostly Revit...
permalink: /:year/:month/:day/:title
markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: falso
